m

diff --git a/changedate b/changedate
--- a/changedate
+++ b/changedate
@@ -26,7 +26,7 @@ plural=
 gotdelta=
 
 usage () {
-myname=$(basename $0)
+myname=${0##*/}
 cat << END
 
 "$myname" changes the timestamp of a given file
@@ -43,9 +43,9 @@ File names containing blanks or wildcards ("*", "?")  must be enclosed in single
 END
 }
 
-if [ $# -eq 0 ]; then
-	echo "Please provide at least a delta time" 1>&2
-	usage 1>&2
+if [[ $# -eq 0 ]]; then
+	echo "Please provide at least a delta time" >&2
+	usage >&2
 	exit 1
 fi
 
@@ -53,9 +53,9 @@ fi
 for arg in "$@"; do
 	# Determine delta value, abort on multiple values
 	if eval echo \'$arg\' | egrep '^[+-]?[[:digit:]]+$' &>/dev/null; then
-		if [ ! -z $gotdelta ]; then
-			echo "Multiple delta values found, please provide only one delta value" 1>&2
-			usage 1>&2
+		if [[  -n "$gotdelta" ]]; then
+			echo "Multiple delta values found, please provide only one delta value" >&2
+			usage >&2
 			exit 1
 		fi
 		delta=$arg
@@ -73,15 +73,15 @@ for arg in "$@"; do
 done
 
 # Error handling
-if [ -z $delta ]; then
-	echo "Please provide a time delta" 1>&2
-	usage 1>&2
+if [[ -z "$delta" ]]; then
+	echo "Please provide a time delta" >&2
+	usage >&2
 	exit 1
 fi
 
-if [ -z $files ]; then
-	echo "Please provide a file name" 1>&2
-	usage 1>&2
+if [[ -z "$files" ]]; then
+	echo "Please provide a file name" >&2
+	usage >&2
 	exit 1
 fi
 
@@ -92,42 +92,42 @@ files=$(echo $files | sed 's/@@++@@/\n/g')
 #### Here we go
 for f in $files; do
 	# Does the file exist?
-	if [ ! -f "$f" ]; then
-		echo "Could not find \"$f\"" 1>&2
+	if [[ ! -f "$f" ]]; then
+		echo "Could not find \"$f\"" >&2
 		((rc++))
 		continue
 	fi
 	new_date=
 	# Get original date, abort on error
 	old_date=$(ls -l --time-style="+%s" "$f" 2> /dev/null | awk -F'\\.| +' '{print $6}' 2> /dev/null)
-	if [ -z $old_date ]; then
-		echo "Could not determine original file date of \"$f\"" 1>&2
+	if [[ -z "$old_date" ]]; then
+		echo "Could not determine original file date of \"$f\"" >&2
 		exit 1
 	fi
 	# Compute new date, abort on error
-	new_date=$(($old_date + $delta))
-	if [ -z $new_date ]; then
-		echo "Could not determine new file date" 1>&2
+	new_date=$(($old_date+$delta))
+	if [[ -z "$new_date" ]]; then
+		echo "Could not determine new file date" >&2
 		exit 1
 	fi
 	new_date_p=$(date -d @$new_date "+%d.%m.%Y %H:%M:%S")
 	new_date=$(date -d @$new_date "+%Y%m%d%H%M.%S")
 
 	# Set new date, don't abort on error
-	if touch -t $new_date "$f"; then
+	if touch -t $new_date "$f" &>/dev/null; then
 		echo "Date of $f has been changed from $(date -d @$old_date '+%d.%m.%Y %H:%M:%S') to $new_date_p"
 	else
-		echo "Could not change date of $f" 1>&2
+		echo "Could not change date of $f" >&2
 		((rc++))
 	fi
 done
 
 # Check for errors
-if [ $rc -ne 0 ]; then
-	if [ $rc -gt 1 ]; then
+if [[ $rc -ne 0 ]]; then
+	if [[ $rc -gt 1 ]]; then
 		plural="s"
 	fi
-	echo "Could not change date of $rc file$plural" 1>&2
+	echo "Could not change date of $rc file$plural" >&2
 	rc=1
 fi
 
diff --git a/deviceinfo b/deviceinfo
--- a/deviceinfo
+++ b/deviceinfo
@@ -14,7 +14,7 @@ device=
 query=
 
 usage() {
-local basename=$(basename $0)
+local basename=${0##*/}
 cat << END
 
 "$basename" prints udev informations about a given device
@@ -27,8 +27,8 @@ END
 }
 
 # We will process only one parameter
-if [ $# -ne 1 ]; then
-	usage 1>&2
+if [[ $# != 1 ]]; then
+	usage >&2
 	exit 1
 else
 	device=$1
@@ -40,8 +40,8 @@ if echo $device | grep -qv '^/dev/'; then
 fi
 
 # Does the device exist?
-if [ ! -e $device ]; then
-	echo "Error: Could not find $device" 1>&2
+if [[ ! -e $device ]]; then
+	echo "Error: Could not find $device" >&2
 	exit 2
 fi
 
@@ -56,14 +56,14 @@ else
 		$query info --attribute-walk --name=$device 
 		rc=$?
 	else
-		echo "Error: Couldn't find udevadm or udevinfo in path" 1>&2
+		echo "Error: Couldn't find udevadm or udevinfo in path" >&2
 		exit 2
 	fi
 fi
 
 rc=$((rc+$?))
 
-if [ $rc -ne 0 ]; then
+if [[ $rc != 1 ]]; then
 	rc=1
 fi
 
diff --git a/getextip_web b/getextip_web
--- a/getextip_web
+++ b/getextip_web
@@ -37,7 +37,7 @@ if AWK=$(which awk 2>/dev/null); then
 		AWK="$AWK --re-interval"
 	fi 
 else
-	echo "Could not find awk, bailing out." 1>&2
+	echo "Could not find awk, bailing out." >&2
 	exit 1
 fi
 
@@ -48,7 +48,7 @@ else
 	if CURL=$(which curl 2>/dev/null); then
 		get="$CURL -s --retry 1 --connect-timeout 10"
 	else
-		echo "Could not find wget or curl, bailing out." 1>&2
+		echo "Could not find wget or curl, bailing out." >&2
 		exit 1
 	fi
 fi
@@ -63,21 +63,21 @@ else
 		# Extract IP address from HTML
 		ip_address=$(echo "$ip_address" | awk -F'<|: +' '{print $(NF-2)}')
 	else
-		echo "Error: No external website is reachable, unable to obtain external IP address" 1>&2
+		echo "Error: No external website is reachable, unable to obtain external IP address" >&2
 		exit 1
 	fi
 fi
 
 # Test obtained string
-if [ -z $ip_address ];then
-	echo "Could not obtain external IP address, got an empty string" 1>&2
+if [[ -z "$ip_address" ]]; then
+	echo "Could not obtain external IP address, got an empty string" >&2
 	exit 1
 fi
 
 ip_test=$(echo "$ip_address" | $AWK -F'.' '$0 ~ /^([0-9]{1,3}\.){3}[0-9]{1,3}$/ && $1 <=255 && $2 <= 255 && $3 <= 255 && $4 <= 255')
 
-if [ -z $ip_test ]; then
-	echo "Error: Obtained string \"$ip_address\" is not a valid IP address" 1>&2
+if [[ -z "$ip_test" ]]; then
+	echo "Error: Obtained string \"$ip_address\" is not a valid IP address" >&2
 	exit 1
 else
 	echo "External IP address is $ip_address"
diff --git a/makeheader b/makeheader
--- a/makeheader
+++ b/makeheader
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 ############################################################
 # makeheader
@@ -35,17 +35,17 @@ filetype=
 
 usage () {
 
-cat << END 1>&2
+cat << END >&2
 
-Usage:   `basename $0` <name_of_file> [bash|sh|[perl|pl]]
-Example: `basename $0` ~/bin/blafasel.sh bash
+Usage:   ${0##*/} <name_of_file> [bash|sh|[perl|pl]]
+Example: ${0##*/} ~/bin/blafasel.sh bash
 
 If only a file name is given, the file type will be sh
 
 END
 }
 
-if [ $# -lt 1 -o $# -gt 2 ]; then
+if [[ $# -lt 1 || $# -gt 2 ]]; then
 	usage
 	exit 1
 fi
@@ -63,36 +63,32 @@ case $filetype in
 	"")
 		;;
 	*)
-		echo "Unknown file type ($filetype)" 1>&2
+		echo "Unknown file type ($filetype)" >&2
 		usage
 		exit 1
 esac
 
-filename_short=`basename $filename`
+filename_short=${filename##*/}
 
 # Some basic tests
-if [ "$filename_short" == "" ]; then
-	echo "Could not determine file name from $filename" 1>&2
+if [[ -z "$filename_short" ]]; then
+	echo "Could not determine file name from $filename" >&2
 	exit 1
 fi
 
-if [ -f $filename ]; then
-	echo "File \"$filename\" exists, chose another name" 1>&2
+if [[ -f $filename ]]; then
+	echo "File \"$filename\" exists, chose another name" >&2
 	exit 1
 fi
 
 # Here we go
-if `touch $filename` > /dev/null; then
-	:
-else
-	echo "Could not create $filename" 1>&2
+if ! touch $filename &> /dev/null; then
+	echo "Could not create $filename" >&2
 	exit 1
 fi
 
-if `chmod +x $filename`; then
-	:
-else
-	echo "Could not change file mode to executable" 1>&2
+if ! chmod +x $filename &> /dev/null; then
+	echo "Could not change file mode to executable" >&2
 	exit 1
 fi
 
diff --git a/mondobackup b/mondobackup
--- a/mondobackup
+++ b/mondobackup
@@ -29,13 +29,13 @@ temp="/mnt/mondo.$$"
 cleanup () {
 if mount | grep -q $temp; then
 	if ! umount $temp &> /dev/null; then
-		echo "Could not unmount temporary directory" 1>&2
+		echo "Could not unmount temporary directory" >&2
 		exit 2
 	fi
 fi
-if [ -d $temp ]; then
+if [[ -d "$temp" ]]; then
 	if ! 'rm' -rf $temp &> /dev/null; then
-		echo "Could not remove temporary directory" 1>&2
+		echo "Could not remove temporary directory" >&2
 		exit 2
 	fi
 fi
@@ -48,30 +48,30 @@ trap 'echo "Program aborted"; exit 3' 1 2 3 15
 ## Checking
 # Where is our executable?
 if ! which mondoarchive &> /dev/null; then
-	echo "Could not find \"mondoarchive\", bailing out" 1>&2
+	echo "Could not find \"mondoarchive\", bailing out" >&2
 	exit 1
 fi
 
 # Does backup directory exist and is readable?
-if [ -d "$backup_dir" ]; then
+if [[ -d "$backup_dir" ]]; then
 	if [ !  -w "$backup_dir" ]; then
-		echo "Backup directory is not writeable, bailing out" 1>&2
+		echo "Backup directory is not writeable, bailing out" >&2
 		exit 1
 	fi
 else
-	echo "Could not find backup directory, bailing out" 1>&2
+	echo "Could not find backup directory, bailing out" >&2
 	exit 1
 fi
 
 # Create temporary directory
 if ! mkdir $temp &> /dev/null; then
-	echo "Could not create temporary directory, bailing out" 1>&2
+	echo "Could not create temporary directory, bailing out" >&2
 	exit 1
 fi
 
 # Mount tmpfs to temporary directory
 if ! mount -t tmpfs -o size=${ram_size},nr_inodes=4k,mode=700 tmpfs $temp &> /dev/null; then
-	echo "Could not mount temporary directory, bailing out" 1>&2
+	echo "Could not mount temporary directory, bailing out" >&2
 	exit 1
 fi
 
@@ -79,7 +79,7 @@ fi
 if mondoarchive -i -O -E "$excluded_dirs" -N -d $backup_dir -s $iso_size -7 -G -T $temp -S $temp -p $(hostname -s)_$(date '+%Y%m%d'); then
 	'mv' /var/cache/mindi/mondorescue.iso $backup_dir
 else
-	echo "mondoarchive exited with error" 1>&2
+	echo "mondoarchive exited with error" >&2
 	exit 1
 fi
 
diff --git a/ppp_stat b/ppp_stat
--- a/ppp_stat
+++ b/ppp_stat
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 
-############################################################
+################################################################################
 # ppp_stat
 #
 # Prints NIC statistics from /proc/net/dev for MRTG
@@ -11,83 +11,81 @@
 # [<uptime>|<error_message>]
 # <short_hostname>
 #
-# Using SNMP for ppp0 was unreliable because as the
-# interface is dropped and activated again the PPP entries
-# would be multiplicated
+# Using SNMP for ppp0 was unreliable because as the interface is dropped and
+# activated again the PPP entries would get multiplicated
 #
 # WS 20100224
-############################################################
+################################################################################
 ########## Changes ##########
 ####
 # Minor improvements
 # WS 20110415
 ####
 
-rc=0
-result=
+RC=0
+RESULT=
 
 # Check for parameters
-if [ "$1" == "" ]; then
-	interface="ppp[0-9]"
+if [[ $# = 0 ]]; then
+	INTERFACE="ppp[0-9]"
 else
-	interface="$1"
+	INTERFACE="$1"
 fi
 
 # Print a neat human readable uptime
 uptm () {
-expr="/usr/bin/expr"
-awk="/bin/awk"
-echo="/bin/echo"
-bc="/usr/bin/bc"
+local AWK="/bin/awk"
+local ECHO="/bin/echo"
+local BC="/usr/bin/bc"
 
 
-t=`cat /proc/uptime`
-day=days
-hour=hours
-min=minutes
+local T=$(cat /proc/uptime)
+local DAY=days
+local HOUR=hours
+local MIN=minutes
 
 # Uptime in fraction of days for MRTG
 
-t=`echo $t | cut -d '.' -f 1`
-d=`echo "$t / 86400" | $bc`
-if [ $d -eq 1 ]; then
-        day=day
+T=${T%%.*}
+local D=$((T/86400))
+if [[ $D = 1 ]]; then
+        DAY=day
 fi
 
-t=`echo "$t % 86400" | $bc`
-h=`echo "$t / 3600" | $bc`
-if [ $h -eq 1 ]; then
-        hour=hour
+T=$(echo "$T%86400" | $BC)
+local H=$(echo "$T/3600" | $BC)
+if [[ $H = 1 ]]; then
+        HOUR=hour
 fi
 
-t=`echo "$t % 3600" | $bc`
-m=`echo "$t / 60" | $bc`
-if [ $m -eq 1 ]; then
-        min=minute
+T=$(echo "$T%3600" | $BC)
+local M=$(echo "$T/60" | $BC)
+if [[ $M = 1 ]]; then
+        MIN=minute
 fi
 
-echo "$d $day, $h $hour and $m $min"
+echo "$D $DAY, $H $HOUR and $M $MIN"
 }
 
 # Get statistics
-result=`awk '/'"$interface"'/ {print $2,$10}' /proc/net/dev`
+RESULT=$($AWK '/'"$INTERFACE"'/ {print $2,$10}' /proc/net/dev)
 
 # Check for errors
-if [ ! "$result" == "" ];then
-	if echo $result | egrep -q '^[0-9]+ +[0-9]+$' 2> /dev/null; then
-		/bin/echo -e `echo $result | sed 's/ /\\\n/'`
+if [[ -n "$RESULT" ]]; then
+	if echo $RESULT | egrep -q '^[0-9]+ +[0-9]+$' 2> /dev/null; then
+		$ECHO -e $(echo $RESULT | sed 's/ /\\\n/')
 		uptm
 	else
-		/bin/echo -e "0\n0\nError: Something is wrong with the result ($result), I expected two integers"
-		rc=1
+		$ECHO -e "0\n0\nError: Something is wrong with the result ($RESULT), I expected two integers"
+		RC=1
 	fi
 		
 else
-	/bin/echo -e "0\n0"
+	$ECHO -e "0\n0"
 	uptm
 fi
-hostname | cut -d '.' -f 1
+hostname -s | cut -d '.' -f 1
 
-exit $rc
+exit $RC
 
 # EOF
diff --git a/show_start_order b/show_start_order
--- a/show_start_order
+++ b/show_start_order
@@ -31,22 +31,20 @@ started_daemons=
 # Set exit code to 2 on abort
 trap 'exit 2' 1 2 3 15
 
-if cd /etc/rc.d/init.d; then
-	:
-else
-	echo "Could not change into /etc/rc.d/init.d, bailing out." 1>&2
-	exit 2
+if ! cd /etc/rc.d/init.di &> /dev/null; then
+	echo "Could not change into /etc/rc.d/init.d, bailing out." >&2
+	exit 1
 fi
 
 # Let's see how we were called
-case $(basename $0) in
+case ${0##*/} in
 	show_start_order)
 		column=1 ;;
 	show_stop_order)
 		column=0 ;;
 	*)
-		echo "Couldn't recognise my own name (\"$(basename $0)\"), bailing out" 1>&2
-		exit 2
+		echo "Couldn't recognise my own name (\"${0##*/}\"), bailing out" >&2
+		exit 1
 		;;
 esac
 
@@ -60,8 +58,8 @@ for d in $started_daemons ; do
 	d1=$d
 	d=$(echo "$all_daemons" | grep $d'$')
 
-	if [ "$d" == "\n" -o "$d" == "" ]; then
-		echo "Testing \"$d1\" failed" 1>&2
+	if [[ "$d" == "\n" || -z "$d" ]]; then
+		echo "Testing \"$d1\" failed" >&2
 		rc=1
 	fi
 
diff --git a/stopvms b/stopvms
--- a/stopvms
+++ b/stopvms
@@ -20,7 +20,7 @@ vm=
 name=
 uid=
 
-if ! [ -x "`which $vboxmanage 2>/dev/null`" ]; then
+if ! [[ -x "$(which $vboxmanage 2>/dev/null)" ]]; then
 	echo "Could not find command VBoxManage"
 	exit 1
 fi
@@ -35,7 +35,7 @@ for vm in $vms; do
 
 # Construct command line:
 # If we're run as root, we need execute $vboxmanage with su
-if [ $root -eq 1 ]; then
+if [[ $root = 1 ]]; then
 	local savestate="su - $user -c \"$vboxmanage controlvm $uid savestate\""
 	local acpi="su - $user -c \"$vboxmanage controlvm $uid acpipowerbutton\""
 	local poweroff="su - $user -c \"$vboxmanage controlvm $uid poweroff\""
@@ -47,11 +47,11 @@ fi
 	# Running escalated shutdown tries, from saving state to poweroff
 	# "eval" is needed because our command string contains quotes
 	if ! eval $savestate 2> /dev/null; then
-		echo "Could not save state of VM $name, trying ACPI shutdown" 1>&2
+		echo "Could not save state of VM $name, trying ACPI shutdown" >&2
 		if ! eval $acpi 2> /dev/null; then
-			echo "ACPI shutdown for VM $name failed, trying poweroff" 1>&2
+			echo "ACPI shutdown for VM $name failed, trying poweroff" >&2
 			if ! eval $poweroff 2> /dev/null; then
-				echo "Could not shut down VM $name, UID $uid" 1>&2
+				echo "Could not shut down VM $name, UID $uid" >&2
 				((rc++))
 			else
 				echo "Poweroff of VM $name successful"
@@ -67,10 +67,10 @@ done
 }
 
 # Check for root rights
-if [ "$(id -u)" != "0" ]; then
+if [[ "$(id -u)" != "0" ]]; then
 	# Get list of running VMs
 	vms=$($vboxmanage list runningvms | awk -F' +|{|}' '{print $1,$(NF-1)}' 2>/dev/null)
-	if [ "$vms" == "" ]; then
+	if [[ -z "$vms" ]]; then
 		echo "Nothing to do"
 		exit 0
 	else
@@ -80,14 +80,14 @@ else
 	root=1
 	# Search for users running VMs
 	users=$(ps -ef | awk '(/VBoxHeadless/ || /VirtualBox/) && /-startvm/ && $8 !~/^awk$/ {print $1}' | sort -u)
-	if [ "$users" == "" ]; then
+	if [[ -z "$users" ]]; then
 		echo "Nothing to do"
 		exit 0
 	else
 		# List VMs run by $user
 		for user in $users ; do
 			vms=$(su - $user -c "$vboxmanage list runningvms" | awk -F' +|{|}' '{print $1,$(NF-1)}' 2>/dev/null)
-			if [ ! "$vms" == "" ]; then
+			if [[ -n "$vms" ]]; then
 				echo "Stopping VMs for user ${user}:"
 				switchoff
 			fi
diff --git a/stopvms_local b/stopvms_local
--- a/stopvms_local
+++ b/stopvms_local
@@ -17,15 +17,15 @@ vm=
 name=
 uid=
 
-if ! [ -x "`which $vboxmanage 2>/dev/null`" ]; then
-	echo "Could not find command VBoxManage" 1>&2
+if ! [[ -x "$(which $vboxmanage 2>/dev/null)" ]]; then
+	echo "Could not find command VBoxManage" >&2
 	exit 1
 fi
 
 # Get list of running VMs
 vms=$($vboxmanage list runningvms | awk -F'{|}' '{print $1,$(NF-1)}' 2>/dev/null)
 
-if [ "$vms" == "" ]; then
+if [[ -z "$vms" ]]; then
 	echo "Nothing to do"
 	exit 0
 fi
@@ -36,11 +36,11 @@ for vm in $vms; do
 	echo "Shutting down $name"
 	# Running escalated shutdown tries, from saving state to poweroff
 	if ! $vboxmanage controlvm $uid savestate 2> /dev/null; then
-		echo "Could not save state of VM $name, trying ACPI shutdown" 1>&2
+		echo "Could not save state of VM $name, trying ACPI shutdown" >&2
 		if ! $vboxmanage controlvm $uid acpipowerbutton 2> /dev/null; then
-			echo "ACPI shutdown for VM $name failed, trying poweroff" 1>&2
+			echo "ACPI shutdown for VM $name failed, trying poweroff" >&2
 			if ! $vboxmanage controlvm $uid poweroff 2> /dev/null; then
-				echo "Could not shut down VM $name, UID $uid" 1>&2
+				echo "Could not shut down VM $name, UID $uid" >&2
 				((rc++))
 			else
 				echo "Poweroff of VM $name successful"
diff --git a/suspend b/suspend
--- a/suspend
+++ b/suspend
@@ -18,7 +18,7 @@
 
 process=BackupPC_dump
 wait_time=5m
-log=/tmp/$(basename $0).log
+log=/tmp/${0##*/}.log
 
 start_time=$(date '+%s')
 counter=0
@@ -29,28 +29,26 @@ prc=
 
 
 # Check if log file is accessible
-if touch $log > /dev/null 2>&1; then
-	:
-else
-	echo "Could not access log file $log" 1>&2
+if ! touch $log > /dev/null 2>&1; then
+	echo "Could not access log file $log" >&2
 	exit 1
 fi
 
 # Check periodically if process is running
-while [ $is_running -eq 1 ]; do
+while [[ $is_running = 1 ]]; do
 	prc=$(/usr/local/bin/psgrep $process | awk '!/BackupPC -d/ && ! /BackupPC_trashClean/')
-	if [ "$prc" == "" ]; then
+	if [[ -z "$prc" ]]; then
 		is_running=0
 	else
 		((counter++))
-		/bin/sleep $wait_time
+		sleep $wait_time
 	fi
 done
 
 # Compute run time
 end_time=$(date '+%s')
 
-if [ $counter -gt 0 ]; then
+if [[ $counter -gt 0 ]]; then
 	exec_time=$(($(($end_time-$start_time))/60))
 fi
 
diff --git a/unlock_pdf b/unlock_pdf
--- a/unlock_pdf
+++ b/unlock_pdf
@@ -19,9 +19,9 @@ rc=0
 usage () {
 cat << END
 
-`basename $0` unlocks a given PDF file
+${0##*/} unlocks a given PDF file
 
-Usage: `basename $0` <pdf_file>
+Usage: ${0##*/} <pdf_file>
 
 The unlocked PDF file can be found in the same directory as the original file, with "_unlocked" appended to the file name.
 
@@ -31,41 +31,35 @@ END
 
 #### Error correction
 # Check if gs exists
-if which gs &> /dev/null; then
-	:
-else
+if ! which gs &> /dev/null; then
 	echo "\"gs\" is not in path (${PATH}). You might want to install the package \"ghostscript\" or check your PATH settings."
 	exit 1
 fi
 
 # Do we have a file name?
-if [ -z "$input" ]; then
+if [[ -z "$input" ]]; then
 	usage
 	exit 1
 
 fi
 
 # Does the file exist?
-if [ -r "$input" ]; then
-	:
-else
-	echo "ERROR: Could not find PDF file ${input}."
+if [[ ! -r "$input" ]]; then
+	echo "Error: Could not find PDF file ${input}."
 	exit 1
 fi
 
 # Is the file a PDF document?
-if file "$input" 2>&1 | grep "PDF document" &> /dev/null; then
-	:
-else
-	echo "ERROR: $input is not a PDF document."
+if ! file "$input" 2> /dev/null | grep -q "PDF document" &> /dev/null; then
+	echo "Error: $input is not a PDF document."
 	usage
 	exit 1
 fi
 
 # Setting target file name
-output="`dirname \"${input}\"`/`basename "$input" .pdf`_unlocked.pdf"
-if [ "$output" == "" -o "$output" == "$input" ]; then
-	echo "ERROR: Could not set output file name. Are \"basename\" and \"dirname\" installed and in path?"
+output="$(echo $input | sed 's/\.[pP][dD][fF]$/_unlocked.pdf/')"
+if [[ -z "$output" || "$output" == "$input" ]]; then
+	echo "Error: Could not set output file name."
 	exit 1
 fi
 
@@ -77,7 +71,7 @@ echo "Writing to ${output}..."
 gs -q -dSAFER -dBATCH -dNOPAUSE -sDEVICE=pdfwrite -sPDFPassword="" -dPDFSETTINGS=/prepress -dPassThroughJPEGImages=true -sOutputFile="$output" "$input"
 rc=$?
 
-if [ $rc -eq 0 ]; then
+if [[ $rc = 0 ]]; then
 	echo "...done."
 else
 	echo "...done with errors. Please check ${output}."
