Linting

diff --git a/check_mrtg b/check_mrtg
--- a/check_mrtg
+++ b/check_mrtg
@@ -7,18 +7,6 @@
 #
 # WS 20110216
 ############################################################
-########## Changes ##########
-####
-# Added editing capability
-# WS 20110305
-####
-# Added error statement on exit and colourised messages
-# WS 20110311
-####
-# Added root check
-# WS 20110417
-####
-
 
 # Make sure we're run by root
 if [[ "$(id -u)" != "0" ]]; then
@@ -44,7 +32,7 @@ target_temp_mb=
 
 
 cleanup () {
-rm -f $temp &>/dev/null
+rm -f "$temp" &>/dev/null
 }
 
 # Always exit cleanly
@@ -52,18 +40,16 @@ trap 'cleanup' 0
 trap 'cleanup; exit 2' 1 2 3 15
 
 # Get OIDs
-if snmpwalk -O n -v 2c -c public localhost .1.3.6.1.4.1.2021.13.16 > $temp 2> /dev/null; then
-	:
-else
-	echo -e "\e[01;31m`basename $0`: Could not perform snmpwalk\e[00m"
+if ! snmpwalk -O n -v 2c -c public localhost .1.3.6.1.4.1.2021.13.16 > "$temp" 2> /dev/null; then
+	echo -e "\e[01;31m${0##*/}: Could not perform snmpwalk\e[00m"
 	exit 1
 fi
 
 i=0
 for item in ${items[*]}; do
 	# Find OID and change from index to value
-	oids[${i}]=$(awk -F'\\\\.| =' '/'"$item"'/ {$(NF-2)=$(NF-2)+1; { for (i = 2; i < NF; ++i) printf "."$i }}' $temp)
-	oid_temp=$(sed 's/\./\\./g' <<<$oids[${i}])
+	oids[${i}]=$(awk -F'\\\\.| =' '/'"$item"'/ {$(NF-2)=$(NF-2)+1; { for (i = 2; i < NF; ++i) printf "."$i }}' "$temp")
+	oid_temp=$(sed 's/\./\\./g' <<<"${oids[$i]}")
 
 	# Search for OID in mrtg.cfg
 	if [[ -z "$(awk '/'"${mrtg_key[${i}]}"'/ && /'"${oid_temp}"'/ && /@/ && ! /^#/' $mrtg_cfg)" ]]; then
@@ -79,7 +65,7 @@ done
 
 
 if [ $found_errors -gt 0 ]; then
-	echo -e "\e[01;32mErrors found, correcting, please check $mrtg_cfg\e[00m"
+	echo -e "\e[01;33mErrors found, correcting, please check $mrtg_cfg\e[00m"
 	# Build target lines for MRTG
 	target_fans="Target[fans]: ${oids[0]}\\&${oids[1]}:Mupfel@127.0.0.1"
 	target_cpu_temp="Target[cpu_temp]: ${oids[2]}\\&${oids[2]}:Mupfel@127.0.0.1"
@@ -97,7 +83,7 @@ else
 fi
 
 if [[ $rc -gt 0 ]]; then
-	echo -e "\e[01;32m$(basename $0) exited with errors\e[00m"
+	echo -e "\e[01;31m${0##*/} exited with errors\e[00m"
 	rc=1
 fi
 
diff --git a/unlock_pdf b/unlock_pdf
--- a/unlock_pdf
+++ b/unlock_pdf
@@ -6,15 +6,9 @@
 #
 # WS 20110216
 ###############################################################
-########## Changes ##########
-####
-# Added quotes to $output/$input so that filenames with blanks
-# can be handled
-# WS 20110715
-####
 
-input=$1
-rc=0
+INPUT=$1
+RC=0
 
 usage () {
 cat << END
@@ -37,46 +31,46 @@ if ! command -v gs &> /dev/null; then
 fi
 
 # Do we have a file name?
-if [[ -z "$input" ]]; then
+if [[ -z "$INPUT" ]]; then
 	usage >&2
 	exit 1
 
 fi
 
 # Does the file exist?
-if [[ ! -r "$input" ]]; then
+if [[ ! -r "$INPUT" ]]; then
 	echo "Error: Could not find PDF file ${input}." >&2
 	exit 1
 fi
 
 # Is the file a PDF document?
-if ! file "$input" 2> /dev/null | grep -q "PDF document" &> /dev/null; then
-	echo "Error: $input is not a PDF document." >&2
+if ! file "$INPUT" 2> /dev/null | grep -q "PDF document" &> /dev/null; then
+	echo "Error: $INPUT is not a PDF document." >&2
 	usage >&2
 	exit 1
 fi
 
 # Setting target file name
-output="$(sed 's/\.[pP][dD][fF]$/_unlocked.pdf/' <<<$input)"
-if [[ -z "$output" || "$output" == "$input" ]]; then
+OUTPUT="$(sed 's/\.[pP][dD][fF]$/_unlocked.pdf/' <<<"$INPUT")"
+if [[ -z "$OUTPUT" || "$OUTPUT" == "$INPUT" ]]; then
 	echo "Error: Could not set output file name." >&2
 	exit 1
 fi
 
 # We'll remove the output file if the progam is aborted
-trap 'rm -rf "${output}" &> /dev/null; echo "Programm aborted" >&2; exit 99' 1 2 3 15
+trap 'rm -rf "${OUTPUT}" &> /dev/null; echo "Programm aborted" >&2; exit 99' 1 2 3 15
 
 #### Here we go
-echo -n "Writing to ${output}... "
-gs -q -dSAFER -dBATCH -dNOPAUSE -sDEVICE=pdfwrite -sPDFPassword="" -dPDFSETTINGS=/prepress -dPassThroughJPEGImages=true -sOutputFile="$output" "$input" 2>/dev/null
-rc=$?
+echo -n "Writing to ${OUTPUT}... "
+gs -q -dSAFER -dBATCH -dNOPAUSE -sDEVICE=pdfwrite -sPDFPassword="" -dPDFSETTINGS=/prepress -dPassThroughJPEGImages=true -sOutputFile="$OUTPUT" "$INPUT" 2>/dev/null
+RC=$?
 
-if [[ $rc = 0 ]]; then
+if [[ $RC = 0 ]]; then
 	echo "...done."
 else
-	echo "...done with errors. Please check ${output}."
+	echo "...done with errors. Please check ${OUTPUT}."
 fi
 
-exit $rc
+exit $RC
 
 # EOF
