Changed order of udevadm/udevinfo detection for SLES

diff --git a/deviceinfo b/deviceinfo
--- a/deviceinfo
+++ b/deviceinfo
@@ -1,26 +1,30 @@
 #!/bin/bash
 
-############################################################
+################################################################################
 # deviceinfo
 #
 # Print udev informations about a given device
-# Tested on Fedora 14, Ubuntu 10.10, Red Hat EL/CentOS 5.5
+# Tested on Fedora 14, Ubuntu 10.10, Red Hat EL/CentOS 5.5, SLES 11
 #
 # WS 20110420
-############################################################
+################################################################################
+########## Changes ##########
+####
+# Changed order of udevadm/udevinfo detection for SLES
+# WS 20111110
 
-rc=0
-device=
-query=
+RC=0
+DEVICE=
+QUERY=
 
 usage() {
-local basename=${0##*/}
+local BASENAME=${0##*/}
 cat << END
 
-"$basename" prints udev informations about a given device
+"$BASENAME" prints udev informations about a given device
 
-Usage:   $basename <device>
-Example: $basename /dev/sda
+Usage:   $BASENAME <device>
+Example: $BASENAME /dev/sda
 
 If the device name doesn't start with "/dev/" it will automatically prefixed with "/dev/"
 END
@@ -31,42 +35,41 @@ if [[ $# != 1 ]]; then
 	usage >&2
 	exit 1
 else
-	device=$1
+	DEVICE=$1
 fi
 
 # If the device doesn't start with "/dev/" prefix it with "/dev/"
-if grep -qv '^/dev/' <<<$device; then
-	device=${device/#/\/dev\/}
+if grep -qv '^/dev/' <<<$DEVICE; then
+	DEVICE=${DEVICE/#/\/dev\/}
 fi
 
 # Does the device exist?
-if [[ ! -e $device ]]; then
-	echo "Error: Could not find $device" >&2
+if [[ ! -e $DEVICE ]]; then
+	echo "Error: Could not find $DEVICE" >&2
 	exit 2
 fi
 
 
 # Get device info with either "udevinfo" or "udevadm"
-if query=$(which udevinfo 2> /dev/null); then
-	$query -a -p $(udevinfo -q path -n $device)
-	rc=$?
+if QUERY=$(which udevadm 2> /dev/null); then
+	$QUERY info --attribute-walk --name=$DEVICE 
+	RC=$?
 else
-
-	if query=$(which udevadm 2> /dev/null); then
-		$query info --attribute-walk --name=$device 
-		rc=$?
+	if QUERY=$(which udevinfo 2> /dev/null); then
+		$QUERY -a -p $(udevinfo -q path -n $DEVICE)
+		RC=$?
 	else
 		echo "Error: Couldn't find udevadm or udevinfo in path" >&2
 		exit 2
 	fi
 fi
 
-rc=$((rc+$?))
+RC=$((RC+$?))
 
-if [[ $rc != 1 ]]; then
-	rc=1
+if [[ $RC != 1 ]]; then
+	RC=1
 fi
 
-exit $rc
+exit $RC
 
 # EOF
