m

diff --git a/getextip_web b/getextip_web
--- a/getextip_web
+++ b/getextip_web
@@ -31,14 +31,14 @@ ip_address=
 ip_test=
 
 # Look for awk
-if ! AWK=$(which awk 2>/dev/null); then
-	echo "Could not find awk, bailing out." 1>&2
-	exit 1
-else
+if AWK=$(which awk 2>/dev/null); then
 	# If we have the GNU version, we need --reinterval
 	if $AWK --version | grep -q GNU; then
 		AWK="$AWK --re-interval"
 	fi 
+else
+	echo "Could not find awk, bailing out." 1>&2
+	exit 1
 fi
 
 # Look for wget or curl
@@ -75,6 +75,7 @@ if [ -z $ip_address ];then
 fi
 
 ip_test=$(echo "$ip_address" | $AWK -F'.' '$0 ~ /^([0-9]{1,3}\.){3}[0-9]{1,3}$/ && $1 <=255 && $2 <= 255 && $3 <= 255 && $4 <= 255')
+
 if [ -z $ip_test ]; then
 	echo "Error: Obtained string \"$ip_address\" is not a valid IP address" 1>&2
 	exit 1
