Minor changes

diff --git a/getextip_web b/getextip_web
--- a/getextip_web
+++ b/getextip_web
@@ -26,27 +26,27 @@
 AWK=
 CURL=
 WGET=
-get=
-ip_address=
-ip_test=
+GET=
+IP_ADDRESS=
+IP_TEST=
 
 # Look for awk
 if AWK=$(which awk 2>/dev/null); then
 	# If we have the GNU version, we need --reinterval
-	if $AWK --version | grep -q GNU; then
+	if $AWK --version 2>/dev/null | grep -q GNU; then
 		AWK="$AWK --re-interval"
 	fi 
 else
-	echo "Could not find awk, bailing out." >&2
+	echo "Could not find GNU awk, bailing out." >&2
 	exit 1
 fi
 
 # Look for wget or curl
 if WGET=$(which wget 2>/dev/null); then
-	get="$WGET --no-cache -q -O - -t 1 -T 10"
+	GET="$WGET --no-cache -q -O - -t 1 -T 10"
 else
 	if CURL=$(which curl 2>/dev/null); then
-		get="$CURL -s --retry 1 --connect-timeout 10"
+		GET="$CURL -s --retry 1 --connect-timeout 10"
 	else
 		echo "Could not find wget or curl, bailing out." >&2
 		exit 1
@@ -55,13 +55,13 @@ fi
 
 #### Here we go
 # Get IP address
-if ip_address=$($get http://showip.net/ 2>/dev/null); then
+if IP_ADDRESS=$($GET http://showip.net/ 2>/dev/null); then
 	# Extract IP address from HTML
-	ip_address=$(echo "$ip_address" | awk -F\" '/check_ip/ && /value=/ {print $(NF-1)}')
+	IP_ADDRESS=$(awk -F\" '/check_ip/ && /value=/ {print $(NF-1)}'<<<"$IP_ADDRESS")
 else
-	if ip_address=$($get http://www.whatismyip.org/automation/n09230945.asp 2>/dev/null); then
+	if IP_ADDRESS=$($GET http://www.whatismyip.org/automation/n09230945.asp 2>/dev/null); then
 		# Extract IP address from HTML
-		ip_address=$(echo "$ip_address" | awk -F'<|: +' '{print $(NF-2)}')
+		IP_ADDRESS=$(awk -F'<|: +' '{print $(NF-2)}'<<<"$IP_ADDRESS")
 	else
 		echo "Error: No external website is reachable, unable to obtain external IP address" >&2
 		exit 1
@@ -69,18 +69,18 @@ else
 fi
 
 # Test obtained string
-if [[ -z "$ip_address" ]]; then
+if [[ -z "$IP_ADDRESS" ]]; then
 	echo "Could not obtain external IP address, got an empty string" >&2
 	exit 1
 fi
 
-ip_test=$(echo "$ip_address" | $AWK -F'.' '$0 ~ /^([0-9]{1,3}\.){3}[0-9]{1,3}$/ && $1 <=255 && $2 <= 255 && $3 <= 255 && $4 <= 255')
+IP_TEST=$($AWK -F'.' '$0 ~ /^([0-9]{1,3}\.){3}[0-9]{1,3}$/ && $1 <=255 && $2 <= 255 && $3 <= 255 && $4 <= 255'<<<"$IP_ADDRESS")
 
-if [[ -z "$ip_test" ]]; then
-	echo "Error: Obtained string \"$ip_address\" is not a valid IP address" >&2
+if [[ -z "$IP_TEST" ]]; then
+	echo "Error: Obtained string \"$IP_ADDRESS\" is not a valid IP address" >&2
 	exit 1
 else
-	echo "External IP address is $ip_address"
+	echo "External IP address is $IP_ADDRESS"
 fi
 
 exit 0
