m

diff --git a/show_start_order b/show_start_order
--- a/show_start_order
+++ b/show_start_order
@@ -40,16 +40,18 @@ case `basename $0` in
 	show_stop_order)
 		column=0 ;;
 	*)
-		echo "Can't recognise my own name (`basename $0`), bailing out" 1>&2
+		echo "Can't recognise my own name (\"`basename $0`\"), bailing out" 1>&2
 		exit 2
 		;;
 esac
+
 awk -F":| +|\t+" '/chkconfig:/ { print $(NF-'"$column"')"#"FILENAME }' * | sort -n > $tmp
 started_daemons=`chkconfig --list | awk '/3:on/ {print $1}'`
 
 for d in $started_daemons ; do
 	grep $d $tmp | sed 's/#/ /' >> $tmp1
 done
+
 sort -n $tmp1
 
 exit 0
