m

diff --git a/wine_wrapper b/wine_wrapper
--- a/wine_wrapper
+++ b/wine_wrapper
@@ -34,7 +34,7 @@ prog=
 id=
 
 # Let's see how we were called
-case `basename $0` in
+case $(basename $0) in
 	irfanview)
 		prog="multimedia/irfanview/i_view32.exe" ;;
 	mp3tag)
@@ -66,13 +66,13 @@ case `basename $0` in
 	wine_wrapper)
 		cd $prog_dir
 		for tag in irfanview mp3tag foobar2000 getright atube_catcher avi_tags mp3directcut mp3merge emule totalcmd renamer adc vnc_listener pdfx; do
-			ln -s `basename $0` $tag
+			ln -s $(basename $0) $tag
 			rc=$((rc+$?))
 		done
 		exit $rc ;;
 		
 	*)
-		echo "Couldn't recognise my own name (\"`basename $0`\"), bailing out" 1>&2
+		echo "Couldn't recognise my own name (\"$(basename $0)\"), bailing out" 1>&2
 		exit 2 ;;
 esac
 
@@ -81,9 +81,7 @@ wine ${base}${prog} &> /dev/null &
 # Check program status
 id=$!
 sleep 1
-if kill -0 $id &> /dev/null; then
-	:
-else
+if ! kill -0 $id &> /dev/null; then
 	echo "Could not run ${base}${prog}" 1>&2
 	rc=99
 fi
